micronaut:
  application:
    name: test-course-template
  server:
    port: 10001
    cors:
      enabled: true
  security:
    redirect:
      login-success: /login_success
      login-failure: /login_failure
      logout: /logout
    enabled: true
    authentication: cookie
    endpoints:
      login:
        enabled: true
        path: /users/signin
      logout:
        enabled: true
        path: /users/signout
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: supaDupaSecretThatNobodyWillKnow
        generator:
          access-token:
            expiration: 1500
